import os

from dotenv import load_dotenv

load_dotenv()


def load_envs_list(name: str) -> list[int]:
    data = os.getenv(name)

    return [int(x) for x in data.split(',')] if data else []


class FacePoints:
    FACEMESH_LEFT_EYE_POINT = load_envs_list('FACEMESH_LEFT_EYE_POINT')
    FACEMESH_RIGHT_EYE_POINT = load_envs_list('FACEMESH_RIGHT_EYE_POINT')
    FACEMESH_LIPS_POINT = load_envs_list('FACEMESH_LIPS_POINT')
    FACEMESH_FOREHEAD_CENTER_POINT = load_envs_list('FACEMESH_FOREHEAD_CENTER_POINT')
    FACEMESH_FOREHEAD_TOP_POINT = load_envs_list('FACEMESH_FOREHEAD_TOP_POINT')
    FACEMESH_LEFT_MOUTH = load_envs_list('FACEMESH_LEFT_MOUTH')
    FACEMESH_RIGHT_MOUTH = load_envs_list('FACEMESH_RIGHT_MOUTH')

    FACEMESH_FACE_OUTLYING_POINTS = load_envs_list('FACEMESH_FACE_OUTLYING_POINTS')
    FACEMESH_FACE_HEIGHT_POINTS = load_envs_list('FACEMESH_FACE_HEIGHT_POINTS')

    FACEMESH_NOSE_HEIGHT_POINTS = load_envs_list('FACEMESH_NOSE_HEIGHT_POINTS')
    FACEMESH_LIPS_WIDTH_POINTS = load_envs_list('FACEMESH_LIPS_WIDTH_POINTS')

    FACEMESH_NOSE_TO_LIPS_POINT = load_envs_list('FACEMESH_NOSE_TO_LIPS_POINT')

    FACEMESH_NOSE_LIPS_TRIANGLE = load_envs_list('FACEMESH_NOSE_LIPS_TRIANGLE')
    FACEMESH_FOREHEAD_TRIANGLE = load_envs_list('FACEMESH_FOREHEAD_TRIANGLE')


    FACEMESH_LEFT_EYE_OUTLYING_POINTS = load_envs_list('FACEMESH_LEFT_EYE_OUTLYING_POINTS')
    FACEMESH_RIGHT_EYE_OUTLYING_POINTS = load_envs_list('FACEMESH_RIGHT_EYE_OUTLYING_POINTS')
    FACEMESH_EYES_DISTANCE_POINTS = load_envs_list('FACEMESH_EYES_DISTANCE_POINTS')
    FACEMESH_LEFT_EYE_HEIGHT_POINTS = load_envs_list('FACEMESH_LEFT_EYE_HEIGHT_POINTS')
    FACEMESH_RIGHT_EYE_HEIGHT_POINTS = load_envs_list('FACEMESH_RIGHT_EYE_HEIGHT_POINTS')
    FACEMESH_LEFT_EYEBROW_POINTS = load_envs_list('FACEMESH_LEFT_EYEBROW_POINTS')
    FACEMESH_RIGHT_EYEBROW_POINTS = load_envs_list('FACEMESH_RIGHT_EYEBROW_POINTS')

    FACEMESH_LEFT_EYE_TO_LEFT_EDGE_OF_LIPS = load_envs_list('FACEMESH_LEFT_EYE_TO_LEFT_EDGE_OF_LIPS')
    FACEMESH_RIGHT_EYE_TO_RIGHT_EDGE_OF_LIPS = load_envs_list('FACEMESH_RIGHT_EYE_TO_RIGHT_EDGE_OF_LIPS')

    FACEMESH_MOUTH_POLYGON = load_envs_list('FACEMESH_MOUTH_POLYGON')
    FACEMESH_FACE_POLYGON = load_envs_list('FACEMESH_FACE_POLYGON')
    FACEMESH_NOSE_POLYGON = load_envs_list('FACEMESH_NOSE_POLYGON')
    FACEMESH_FOREHEAD_POLYGON = load_envs_list('FACEMESH_FOREHEAD_POLYGON')
    FACEMESH_LEFT_EYE_POLYGON = load_envs_list('FACEMESH_LEFT_EYE_POLYGON')
    FACEMESH_RIGHT_EYE_POLYGON = load_envs_list('FACEMESH_RIGHT_EYE_POLYGON')
    FACEMESH_LEFT_CHEEK_POLYGON = load_envs_list('FACEMESH_LEFT_CHEEK_POLYGON')
    FACEMESH_RIGHT_CHEEK_POLYGON = load_envs_list('FACEMESH_RIGHT_CHEEK_POLYGON')
    FACEMESH_CHIN_POLYGON = load_envs_list('FACEMESH_CHIN_POLYGON')